### ISSUE TITLE
Garbled output from Gradle

### ISSUE THREAD

**Issue by bpoland** [buildkite/terminal-to-html#143]
Hey, we're seeing very infrequently that Gradle will mangle output, I assume due to some weird control characters. Here's an example:
<img width="1126" alt="image" src="https://github.com/buildkite/terminal-to-html/assets/24273909/43e17e3c-f2dc-4d72-884e-2467223b94ec">

It seems like this could be related to some previous discussions:
- https://github.com/buildkite/terminal-to-html/issues/96 (and #97, #98, #99)
- potentially https://github.com/buildkite/agent/issues/1738 ?

I also found this Gradle issue where the output looks similar but I'm not sure if it's related https://github.com/gradle/gradle/issues/8204

One of the more annoying parts of this issue is that when it happens, it corrupts all the output in the step/job and isn't contained to a single log group. Is there a way that terminal-to-html could prevent control characters from jumping across log groups above it somehow?  It seems unlikely/unexpected that you'd want to go backwards and change log groups above.

Also interested in anyone's thoughts about what could be causing this. I have only seen it happen a few times out of hundreds of builds and I don't know what's different when it does happen...

**Comment by DrJosh9000** [comment]
Hi again @bpoland ! That console output does look funky. For a workaround I think you should try `gradle --console=plain`.

>  Is there a way that terminal-to-html could prevent control characters from jumping across log groups above it somehow? It seems unlikely/unexpected that you'd want to go backwards and change log groups above.

That's a good idea. terminal-to-html itself isn't aware of log groupings, but perhaps we could make it aware.

> Also interested in anyone's thoughts about what could be causing this

Looking through the Gradle bug you linked, it could possibly be related to how the agent doesn't set a window size on the PTY. It'll need more investigating.

**Comment by bpoland** [comment]
> Hi again @bpoland ! That console output does look funky. Have you tried `gradle --console=plain` as a workaround?
Yeah console=plain does work but the richer output is a lot more useful when it does work. It seems like a shame to turn it off just for the 1% or less of runs where the output gets mangled 😢

**Comment by DrJosh9000** [comment]
I have a theory why this is happening only very occasionally, and it relates to some other weird output in (other customers') jobs. There's a chance this is an agent bug (that I added 😣) to do with timestamp insertion.

**Comment by DrJosh9000** [comment]
I've just released v3.73.0 of the agent (and v0.11.0 of the k8s stack) with that fix - give it a whirl and let me know if you see more garbled logs!

**Comment by bpoland** [comment]
Thanks, just to follow up here -- I haven't seen any garbled output since updating, but it was also quite rare anyway :)

I'm good to close this and reopen later if I see it again?

**Comment by DrJosh9000** [comment]
Absolutely, let us know if you see it again!

**Comment by bpoland** [comment]
@DrJosh9000 I just came across a small garble in the output, much less serious than I've seen previously.  This is the only time I've seen anything weird since updating.  The `77% CONFIGURING [59s]` and `> IDLE` lines are left over from when Gradle was running, and don't normally show up after it finishes.

<img width="943" alt="image" src="https://github.com/buildkite/terminal-to-html/assets/24273909/7dd2134a-89d2-4ae9-b096-2ba5ca4cdb52">

So it's possible there is still something a little off, or could very well be a Gradle bug too haha.  I don't think this is worthy of reopening this issue since it's pretty minor but just thought I'd share -- thanks again for the help here!

**Comment by bpoland** [comment]
Just to circle back here again, unfortunately we are still seeing occasional issues with Gradle output getting messed up, similar to my last screenshot :(

I think the fix here definitely improved things as it no longer seems to jump backwards and trample output from previous log groups though!

**Comment by DrJosh9000** [comment]
Hey @bpoland, I've taken another look at your logs and figured it out 😄 

Gradle (which thinks the PTY has a [window size of 160x100](https://github.com/buildkite/agent/blob/b0b52acc42dd34d22e7bd4895ce7ee38be8838f9/process/pty.go#L15-L16)) is moving the cursor back to the start of the line with `\e[159B` instead of `\e[G`, but terminal-to-html is parsing integers like this:

https://github.com/buildkite/terminal-to-html/blob/ff58a3e5ca071c225500c087a64de6c481b456b4/screen.go#L102

limiting the parameter range (-128 to 127). As far as I can tell it has had this limitation ever since the rewrite from Ruby to Go.

**Comment by bpoland** [comment]
👏 woohoo, thanks for digging into this! Excited to try this out :)
